main/urls.py
"""The main application's URLs."""

from django.urls import path

from . import views

app_name = "main"
urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('contest/<contest_id>/', views.contest, name="contest"),
    path('contest/<contest_id>/duel/', views.duel, name="duel"),
]

photoduel/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auth/', include('tokenauth.urls', namespace="tokenauth")),
    path('apcery/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
import bleach
import mistune
import shortuuid
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


def render_markdown(text) -> str:
    """Render Markdown, disallowing some tags and cleaning it up afterwards."""
    allowed_tags = [
        'a', 'abbr', 'acronym', 'b', 'blockquote', 'code', 'em', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'i', 'li', 'ol',
        'p', 'pre', 'span', 'strong', 'ul'
    ]
    allowed_attributes = {
        'a': ['href', 'title'],
        'acronym': ['title'],
        'abbr': ['title'],
        'span': ['data-expounder', 'data-expounded']
    }

    rendered = mistune.markdown(text, escape=False)
    cleaned = bleach.clean(rendered, tags=allowed_tags, attributes=allowed_attributes)
    linkified = bleach.linkify(cleaned)
    return linkified


def generate_username() -> str:
    """Create a UUID."""
    return shortuuid.ShortUUID().random(8)


def generate_uuid() -> str:
    """Create a UUID."""
    return shortuuid.ShortUUID().random(8)


class CharIDModel(models.Model):
    """Base model that gives children string IDs."""

    id = models.CharField(max_length=30, primary_key=True, default=generate_uuid, editable=False)

    class Meta:
        abstract = True


class User(AbstractUser):
    username = models.CharField(
        _('username'),
        max_length=150,
        default=generate_username,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[UnicodeUsernameValidator()],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )


class Contest(CharIDModel):
    PUBLIC = "PU"
    PRIVATE = "PR"

    OPENNESS = [
        (PUBLIC, _("Open")),
        (PRIVATE, _("Private")),
    ]

    SUBMISSION = "SUB"
    VOTING = "VOT"
    COMPLETE = "COM"

    STAGE = [
        (SUBMISSION, _("Submission")),
        (VOTING, _("Voting")),
        (COMPLETE, _("Complete")),
    ]

    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    participation = models.CharField(max_length=200, choices=OPENNESS, default=PUBLIC)
    voting = models.CharField(max_length=200, choices=OPENNESS, default=PUBLIC)
    visibility = models.CharField(max_length=200, choices=OPENNESS, default=PUBLIC)

    stage = models.CharField(max_length=200, choices=STAGE, default=SUBMISSION)

    creation_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_rendered_description(self) -> str:
        return render_markdown(self.description)

    def get_absolute_url(self):
        return reverse('main:contest', args=[self.id])


class Photo(CharIDModel):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    contest = models.ForeignKey(Contest, on_delete=models.CASCADE)
    url = models.CharField(max_length=2000)
    creation_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.id


class Vote(CharIDModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    contest = models.ForeignKey(Contest, on_delete=models.CASCADE)
    winner = models.ForeignKey(Photo, on_delete=models.CASCADE, related_name="winners")
    loser = models.ForeignKey(Photo, on_delete=models.CASCADE, related_name="losers")

    def __str__(self):
        return "%s - %s > %s" % (self.contest, self.winner, self.loser)

main/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import ugettext as _
from django.views.decorators.http import require_http_methods

from .models import Contest, Vote


@require_http_methods(["GET", "POST"])
@login_required
def duel(request, contest_id):
    contest = get_object_or_404(Contest, pk=contest_id)
    if not contest.photo_set.exists():
        messages.error(request, _("That contest doesn't have any photos yet."))
        return redirect(contest)

    if contest.stage != Contest.VOTING:
        if contest.stage == Contest.SUBMISSION:
            messages.error(request, _("Voting on that contest hasn't opened yet."))
        else:
            messages.error(request, _("Voting on that contest has ended."))
        return redirect(contest)

    if request.method == "POST":
        winner = contest.photo_set.filter(pk=request.POST.get("winner_id")).first()
        loser = contest.photo_set.filter(pk=request.POST.get("loser_id")).first()

        if not (winner and loser):
            messages.error(request, _("Invalid photo selected."))
            return redirect("main:duel", contest_id)

        Vote.objects.create(
            user=request.user,
            contest=contest,
            winner=winner,
            loser=loser,
        )
        return redirect("main:duel", contest_id)
    else:
        photo1 = contest.photo_set.all().order_by("?").first()
        photo2 = contest.photo_set.exclude(pk=photo1.id).order_by("?").first()
        return render(request, "duel.html", locals())


def contest(request, contest_id):
    contest = get_object_or_404(Contest, pk=contest_id)
    return render(request, "contest.html", locals())


def index(request):
    return render(request, "index.html")


def login(request):
    return render(request, "login.html")

templates/base.html
{% load i18n %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} - {{ request.site.name }}</title>

    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:300,400" rel="stylesheet">
    <link href="{% static "css/main.css" %}" rel="stylesheet">
</head>
<body>
    <header>
        <a class="brand" href="{% url 'main:index' %}">
            <div class="brand-image">
                <img src="{% static "img/logo.svg" %}" alt="logo" width="30px">
            </div>
            <div class="brand-text">{% trans "Photoduel" %}</div>
        </a>
        <nav>
            {% if request.user.is_authenticated %}
            <a href="{% url "tokenauth:logout" %}" class="nav-item">{% trans "Log out" %}</a>
            {% else %}
            <a href="{% url "main:login" %}" class="nav-item">{% trans "Log in / Sign up" %}</a>
            {% endif %}
        </nav>
    </header>

    {% block content %}
    {% endblock %}
</body>
</html>

templates/contest.html
{% extends "base.html" %}

{% load i18n %}
{% load staticfiles %}

{% block title %}{{ contest.name }}{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ contest.name }}</h1>
    <div class="subtitle">
        {{ contest.get_rendered_description|safe }}
    </div>

    {% if contest.photo_set.exists %}
    <p>
    {% if contest.stage == contest.SUBMISSION %}
    {% trans "Voting on this contest is not open yet." %}
    {% elif contest.stage == contest.VOTING %}
    <a href="{% url "main:duel" contest.id %}">Vote now!</a>
    {% else %}
    {% trans "Voting on this contest has ended." %}
    {% endif %}
    </p>
    {% endif %}

    {% for photo in contest.photo_set.all %}
    <img src="{{ photo.url }}"/>
    {% empty %}
    {% trans "There are no photos in this contest yet." %}
    {% endfor %}
</div>
{% endblock %}

templates/duel.html
{% extends "base.html" %}

{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans "Fight!" %}{% endblock %}

{% block content %}
<div class="container">
    <h1>{% trans "Duel" %}</h1>

    <div class="subtitle">
        {% trans "Which photo is better?" %}
    </div>

    <form method="POST" action="{% url "main:duel" contest.id %}">{% csrf_token %}
        <input type="hidden" name="winner_id" value="{{ photo1.id }}" />
        <input type="hidden" name="loser_id" value="{{ photo2.id }}" />
        <button type="send"><img src="{{ photo1.url }}"/></button>
    </form>

    <form method="POST" action="{% url "main:duel" contest.id %}">{% csrf_token %}
        <input type="hidden" name="winner_id" value="{{ photo2.id }}" />
        <input type="hidden" name="loser_id" value="{{ photo1.id }}" />
        <button type="send"><img src="{{ photo2.url }}"/></button>
    </form>

    <a href="{{ contest.get_absolute_url }}">Back to the contest</a>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans "Home" %}{% endblock %}

{% block content %}
<div class="container">
    <h1>{% trans "Photography Contests" %}</h1>
    <div class="subtitle">
        {% trans "Submit your photographs and let the community vote for the best!" %}
    </div>

    <div class="versus">
        <img class="versus-one" src="{% static "img/versus-pic-one.svg" %}" alt="versus pic one" height="170px">
        <img class="versus-sign" src="{% static "img/versus-sign.svg" %}" alt="versus sign" height="60px">
        <img class="versus-two" src="{% static "img/versus-pic-two.svg" %}" alt="versus pic two" height="170px">
    </div>
</div>
<div class="separator">
    <img src="{% static "img/camera.svg" %}" alt="camera" height="50px">
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans "Sign in" %}{% endblock %}

{% block content %}
<div class="container">
    <h1>{% trans "Log in / Sign up" %}</h1>

    <p class="lead">
    {% blocktrans %}
    To create an account or log in, just enter your email address below. We will send you an email containing a link.
    Click it, and you will be logged in!
    {% endblocktrans %}
    </p>

    <form action="{% url "tokenauth:login" %}?next={{ request.GET.next }}" method="post" class="form-login">
        {% csrf_token %}
        <input name="email" type="email" placeholder="Email">
        <button type="submit">{% trans "Send link" %}</button>
    </form>
</div>
{% endblock %}